// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef tuto05_h
#define tuto05_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *button01;
#include <FL/Fl_Input.H>
extern Fl_Input *input01;
extern Fl_Button *button02;
extern Fl_Button *button03;
extern Fl_Button *button04;
Fl_Double_Window* make_window();
int main();
#endif
